os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '10'
  - '12'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CC=gcc-6; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CC=g++-6; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - npm install winston@3.2.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
  - 'if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo setcap ''cap_net_admin,cap_net_raw,cap_net_bind_service=+eip'' $(eval readlink -f `which node`); echo set caps; fi'
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcap2-bin
      - g++-6
      - libusb-1.0-0.dev
      - libudev-dev
      - arp-scan
      - bluetooth
      - bluez
      - libbluetooth-dev
      - libudev-dev
script:
  - npm run test:package
  - export DEBUG=testing:*
  - node testme
  - npm run test:integration
